<?php

namespace AppBundle\Repository;

use Doctrine\ODM\MongoDB\LockMode;
use Doctrine\MongoDB\Util;
/**
 * TodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodoRepository extends \Doctrine\ODM\MongoDB\DocumentRepository {

//    public function find($id, $lockMode = LockMode::NONE, $lockVersion = null) {
//        //parent::find($id, $lockMode, $lockVersion);
//        $cacheId = 'Todo_findById_'.$id;
//        $cacheId = md5($cacheId);
//        return $this->createQueryBuilder('t')
//         ->field('id')->equals($id)
//         ->getQuery()
//         ->useQueryCache(true)
//         ->useResultCache(true, Util::CACHE_ACTIVITY_FEED, $cacheId)
//         ->getResult();
//    }
}
